apiVersion: batch/v1
kind: Job
metadata:
  name: speedup-test
  namespace: speedup-test
  labels:
    group: test
spec:
  template:
    spec:
      containers:
      - name: speedup-test
        # image: jackvasc/speedup-test:1.0.0
        image: jackvasc/speedup-test
        volumeMounts:
        - name: speedup-test-config
          mountPath: /home/speedup/.kube/config
          subPath: config
        - name: speedup-test-config
          mountPath: /orquestration/scenarios.yml
          subPath: scenarios
        env:
          - name: ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: aws-credentials
                key: ACCESS_KEY
          - name: SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: aws-credentials
                key: SECRET_KEY
          - name: SCENARIOS_FILE
            value: /orquestration/scenarios.yml
      restartPolicy: Never
      volumes:
      - name: speedup-test-config
        configMap:
          name: speedup-test-config