apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - namespace.yaml
  - job.yaml

# disable suffix hash
generatorOptions:
 disableNameSuffixHash: true

# configmap
configMapGenerator:
- name: aws-credentials
  namespace: speedup-test
  envs:
  - aws.env
- name: speedup-test-config
  namespace: speedup-test
  # envs:
  # - speedup-test-config.env
  files:
    # configfile is used as key
    - config=config