apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ${NAME}
spec:
  hosts:
    - "${NAME}"
  http:
    - route:
        - destination:
            port:
              number: ${PORT}
            host: ${NAME}
      fault:
        delay:
          percent: 100
          fixedDelay: ${DELAY}