apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - namespace.yaml
  - job.yaml

# disable suffix hash
generatorOptions:
 disableNameSuffixHash: true

# configmap
configMapGenerator:
- name: aws-credentials
  namespace: k6
  envs:
  - aws.env
- name: k6-config
  namespace: k6
  envs:
  - k6-config.env
  files:
    # configfile is used as key
    - k6-script.js=script.js
    - metrics.json=metrics.json