apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - manifests/adservice.yaml
  - manifests/cartservice.yaml
  - manifests/checkoutservice.yaml
  - manifests/currencyservice.yaml
  - manifests/emailservice.yaml
  - manifests/frontend.yaml
  - manifests/paymentservice.yaml
  - manifests/productcatalogservice.yaml
  - manifests/recommendationservice.yaml
  - manifests/redis-cart.yaml
  - manifests/shippingservice.yaml
patches:
- path: patch.yaml
  target:
    kind: Deployment
commonLabels:
  group: app

# # disable suffix hash
# generatorOptions:
#  disableNameSuffixHash: true

# # configmap
# configMapGenerator:
# - name: hisptershop-config
#   files:
#     # configfile is used as key
#     - GOOGLE_APPLICATION_CREDENTIALS=hipstershop.json