apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: acmeair-main
spec:
  hosts:
    - acmeair-main-service
  http:
    - name: acmeair-main-service
      route:
      - destination:
          port:
            number: 9080
          host: acmeair-main-service
