apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth
spec:
  hosts:
    - acmeair-auth-service
  http:
    - name: acmeair-auth-service
      route:
      - destination:
          port:
            number: 9080
          host: acmeair-auth-service
