apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: booking
spec:
  hosts:
    - acmeair-booking-service
  http:
    - name: acmeair-booking-service
      route:
      - destination:
          port:
            number: 9080
          host: acmeair-booking-service
