apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer
spec:
  hosts:
    - acmeair-customer-service
  http:
    - name: acmeair-customer-service
      route:
      - destination:
          port:
            number: 9080
          host: acmeair-customer-service
