apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flight
spec:
  hosts:
  - "*"
  gateways:
  - acmeair-gateway
  http:
  - match:
    - uri:
        prefix: /flight
    route:
    - destination:
        port:
          number: 9080
        host: acmeair-flight-service
