apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flight
spec:
  hosts:
    - acmeair-flight-service
  http:
    - name: acmeair-flight-service
      route:
      - destination:
          port:
            number: 9080
          host: acmeair-flight-service
